force-app/main/default/objects/Contract/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <description>net total price</description>
    <label>Total Price</label>
    <summarizedField>Contract_Product__c.Subtotal_Price__c</summarizedField>
    <summaryForeignKey>Contract_Product__c.Contract__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contract/fields/Total_Price_with_VAT__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_with_VAT__c</fullName>
    <formula>Total_Price__c * 1.27</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price with VAT</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contract_Product__c/Contract_Product__c.object-meta.xml
<CustomObject>
    <label>Contract Product</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Contract Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Product__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Contract Products</relationshipLabel>
    <relationshipName>Contract_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contract Products</relationshipLabel>
    <relationshipName>Contract_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Product__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract_Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Unit Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContractService.cls
public with sharing class ContractService {
    public Contract contract {get; set;}
    public Contract_Product__c[] contractProducts {get; set;}

    public Contract_Product__c[] queryContractProducts(Id contractId) {
        return [
            SELECT Id
                ,Contract__c
                ,Product__r.Name
                ,Quantity__c
                ,Unit_Price__c
                ,Subtotal_Price__c
            FROM Contract_Product__c
            WHERE Contract__c = :contractId
        ];
    }

    public ContractService(ApexPages.StandardController controller) {
        contract = (Contract)controller.getRecord();
        contractProducts = queryContractProducts(contract.Id);
    }

    public ContractService(Contract inContract) {
        contract = inContract;
        contractProducts = queryContractProducts(contract.Id);
    }

    public ContractService(Id contractId) {
        contract = [SELECT Id
            , StartDate
            , Account.Name
            , Account.BillingCountryCode
            , Account.BillingState
            , Account.BillingCity
            , Account.BillingStreet
            , Total_Price__c
            , Total_Price_with_VAT__c
        FROM Contract WHERE Id = :contractId LIMIT 1];
        contractProducts = queryContractProducts(contract.Id);
    }
}